/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Category_Panel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCategoryName = new javax.swing.JTextField();
        btnCategoryRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCategoryRegID = new javax.swing.JTextField();
        Car_Panel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtCarRegNumber = new javax.swing.JTextField();
        txtCarRegColor = new javax.swing.JTextField();
        btnCarRegister = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        txtCarRegName = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtCarRegID = new javax.swing.JTextField();
        txtCarRegCategory = new javax.swing.JTextField();
        Customer_Panel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtCustomerRegNICNumber = new javax.swing.JTextField();
        txtCustomerRegMobile = new javax.swing.JTextField();
        btnCustomerRegister = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        txtCustomerRegLastName = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        txtCustomerRegID = new javax.swing.JTextField();
        txtCustomerRegFirstName = new javax.swing.JTextField();
        txtCustomerRegAddress = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtSearchCategory = new javax.swing.JTextField();
        btnCategorySearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCategoryView = new javax.swing.JTextArea();
        btnCategoryUpdate = new javax.swing.JButton();
        btnCategoryDelete = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtSearchCar = new javax.swing.JTextField();
        btnCarSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPatientView = new javax.swing.JTextArea();
        btnCarUpdate = new javax.swing.JButton();
        btnCarDelete = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtSearchCustomer = new javax.swing.JTextField();
        btnCustomerSearch = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtCustomerView = new javax.swing.JTextArea();
        btnCustomerUpdate = new javax.swing.JButton();
        btnCustomerDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Category Registration"));

        jLabel5.setText("Name");

        btnCategoryRegister.setText("Register");
        btnCategoryRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryRegisterActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoryName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoryRegID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCategoryRegister, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategoryRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnCategoryRegister)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Category_PanelLayout = new javax.swing.GroupLayout(Category_Panel);
        Category_Panel.setLayout(Category_PanelLayout);
        Category_PanelLayout.setHorizontalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Category_PanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Category_PanelLayout.setVerticalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Category_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Categories", Category_Panel);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Car Registration"));

        jLabel52.setText("Reg Number");

        jLabel53.setText("Category");

        jLabel56.setText("Color");

        btnCarRegister.setText("Register");
        btnCarRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarRegisterActionPerformed(evt);
            }
        });

        jLabel65.setText("Name");

        jLabel70.setText("ID");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCarRegister)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarRegNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarRegID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarRegColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarRegName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtCarRegCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel56)
                                .addComponent(jLabel52)
                                .addComponent(jLabel70)
                                .addComponent(jLabel65)
                                .addComponent(jLabel53)))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(txtCarRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(4, 4, 4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarRegName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(txtCarRegCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(txtCarRegColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnCarRegister)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Car_PanelLayout = new javax.swing.GroupLayout(Car_Panel);
        Car_Panel.setLayout(Car_PanelLayout);
        Car_PanelLayout.setHorizontalGroup(
            Car_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Car_PanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        Car_PanelLayout.setVerticalGroup(
            Car_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Car_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Cars", Car_Panel);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Registration"));

        jLabel54.setText("NIC Number");

        jLabel55.setText("Last Name");

        jLabel57.setText("Mobile");

        btnCustomerRegister.setText("Register");
        btnCustomerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerRegisterActionPerformed(evt);
            }
        });

        jLabel66.setText("First Name");

        jLabel71.setText("ID");

        txtCustomerRegAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerRegAddressActionPerformed(evt);
            }
        });

        jLabel58.setText("Address");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCustomerRegister)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel54)
                            .addComponent(jLabel71)
                            .addComponent(jLabel66)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCustomerRegLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCustomerRegNICNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCustomerRegID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtCustomerRegFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerRegMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerRegAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(txtCustomerRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomerRegNICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addGap(4, 4, 4)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(txtCustomerRegFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(txtCustomerRegLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerRegMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addGap(31, 31, 31)
                .addComponent(btnCustomerRegister)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Customer_PanelLayout = new javax.swing.GroupLayout(Customer_Panel);
        Customer_Panel.setLayout(Customer_PanelLayout);
        Customer_PanelLayout.setHorizontalGroup(
            Customer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Customer_PanelLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        Customer_PanelLayout.setVerticalGroup(
            Customer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Customer_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Customer", Customer_Panel);

        jLabel14.setText("Category ID");

        btnCategorySearch.setText("Search");
        btnCategorySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategorySearchActionPerformed(evt);
            }
        });

        txtCategoryView.setColumns(20);
        txtCategoryView.setRows(5);
        jScrollPane2.setViewportView(txtCategoryView);

        btnCategoryUpdate.setText("Update");
        btnCategoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryUpdateActionPerformed(evt);
            }
        });

        btnCategoryDelete.setText("Delete");
        btnCategoryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(61, 61, 61)
                                .addComponent(txtSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnCategorySearch))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnCategoryUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(btnCategoryDelete)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategorySearch))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoryUpdate)
                    .addComponent(btnCategoryDelete))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Category", jPanel9);

        jLabel15.setText("Car ID");

        btnCarSearch.setText("Search");
        btnCarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarSearchActionPerformed(evt);
            }
        });

        txtPatientView.setColumns(20);
        txtPatientView.setRows(5);
        jScrollPane3.setViewportView(txtPatientView);

        btnCarUpdate.setText("Update");
        btnCarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarUpdateActionPerformed(evt);
            }
        });

        btnCarDelete.setText("Delete");
        btnCarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(70, 70, 70)
                        .addComponent(txtSearchCar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCarSearch))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnCarUpdate)
                        .addGap(76, 76, 76)
                        .addComponent(btnCarDelete)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSearchCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarSearch))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarUpdate)
                    .addComponent(btnCarDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Car", jPanel10);

        jLabel17.setText("Customer ID");

        btnCustomerSearch.setText("Search");
        btnCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSearchActionPerformed(evt);
            }
        });

        txtCustomerView.setColumns(20);
        txtCustomerView.setRows(5);
        jScrollPane5.setViewportView(txtCustomerView);

        btnCustomerUpdate.setText("Update");
        btnCustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerUpdateActionPerformed(evt);
            }
        });

        btnCustomerDelete.setText("Delete");
        btnCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(70, 70, 70)
                        .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCustomerSearch))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnCustomerUpdate)
                        .addGap(76, 76, 76)
                        .addComponent(btnCustomerDelete)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerSearch))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomerUpdate)
                    .addComponent(btnCustomerDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Customer", jPanel17);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarSearchActionPerformed
        Statement s = CarRegMS.getStatement();
        try {

            ResultSet rs = s.executeQuery("SELECT * FROM car WHERE id = '" + txtSearchCar.getText() + "'");

            while (rs.next()) {
                txtPatientView.setText(rs.getString("id"));
                txtPatientView.setText(rs.getString("regNumber"));
                txtPatientView.setText(rs.getString("name"));
                txtPatientView.setText(rs.getString("category"));
                txtPatientView.setText(rs.getString("color"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnCarSearchActionPerformed

    private void btnCarRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarRegisterActionPerformed
        Statement stat = CarRegMS.getStatement();
        try {
            if (txtCarRegID.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Car Registration ID");
            } else if (txtCarRegNumber.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Car Registration Number");
            } else if (txtCarRegName.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Car Registration Name");
            } else if (txtCarRegCategory.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Car Registration Category");
            } else if (txtCarRegColor.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Car Registration Color");
            } else {
                stat.executeUpdate("INSERT INTO car(id,regNumber,name,category,color) VALUES ('" + txtCarRegID.getText() + "','" + txtCarRegNumber.getText() + "','" + txtCarRegName.getText() + "','" + txtCarRegCategory.getText() + "','" + txtCarRegColor.getText() + "')");

                JOptionPane.showMessageDialog(null, "Successful..!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarRegisterActionPerformed

    private void btnCategoryRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryRegisterActionPerformed
        Statement stat = CarRegMS.getStatement();
        try {
            if (txtCategoryRegID.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Category ID");
            } else if (txtCategoryName.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Category Name");
            } else {
                stat.executeUpdate("INSERT INTO category(id,name) VALUES ('" + txtCategoryRegID.getText() + "','" + txtCategoryName.getText() + "')");

                JOptionPane.showMessageDialog(null, "Successful..!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCategoryRegisterActionPerformed

    private void btnCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerRegisterActionPerformed
        Statement stat = CarRegMS.getStatement();
        try {
            if (txtCustomerRegID.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration ID");
            } else if (txtCustomerRegNICNumber.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration NIC Number");
            } else if (txtCustomerRegFirstName.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration First Name");
            } else if (txtCustomerRegLastName.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration Last Name");
            } else if (txtCustomerRegMobile.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration Mobile");
            } else if (txtCustomerRegAddress.getText().length() == 0) {  // Checking for empty field
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Customer Registration Address");
            } else {
                stat.executeUpdate("INSERT INTO customer(id,nic,firstName,lastName,mobile,address) VALUES ('" + 
                        txtCustomerRegID.getText() + "','" + 
                        txtCustomerRegNICNumber.getText() + "','" + 
                        txtCustomerRegFirstName.getText() + "','" + 
                        txtCustomerRegLastName.getText() + "','" + 
                        txtCustomerRegMobile.getText() + "','" + 
                        txtCustomerRegAddress.getText() + "')");

                JOptionPane.showMessageDialog(null, "Successful..!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerRegisterActionPerformed

    private void txtCustomerRegAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerRegAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerRegAddressActionPerformed

    private void btnCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSearchActionPerformed
        Statement s = CarRegMS.getStatement();
        try {

            ResultSet rs = s.executeQuery("SELECT * FROM customer WHERE id = '" + txtSearchCustomer.getText() + "'");

            while (rs.next()) {
                txtCustomerView.setText(rs.getString("id"));
                txtCustomerView.setText(rs.getString("nic"));
                txtCustomerView.setText(rs.getString("firstName"));
                txtCustomerView.setText(rs.getString("lastName"));
                txtCustomerView.setText(rs.getString("mobile"));
                txtCustomerView.setText(rs.getString("address"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerSearchActionPerformed

    private void btnCategorySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategorySearchActionPerformed
        Statement s = CarRegMS.getStatement();
        try {

            ResultSet rs = s.executeQuery("SELECT * FROM category WHERE id = '" + txtSearchCategory.getText() + "'");

            while (rs.next()) {
                txtCategoryView.setText(rs.getString("id"));
                txtCategoryView.setText(rs.getString("name"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategorySearchActionPerformed

    private void btnCategoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoryUpdateActionPerformed

    private void btnCarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarUpdateActionPerformed

    private void btnCustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerUpdateActionPerformed

    private void btnCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerDeleteActionPerformed

    private void btnCarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarDeleteActionPerformed

    private void btnCategoryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoryDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Car_Panel;
    private javax.swing.JPanel Category_Panel;
    private javax.swing.JPanel Customer_Panel;
    private javax.swing.JButton btnCarDelete;
    private javax.swing.JButton btnCarRegister;
    private javax.swing.JButton btnCarSearch;
    private javax.swing.JButton btnCarUpdate;
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryRegister;
    private javax.swing.JButton btnCategorySearch;
    private javax.swing.JButton btnCategoryUpdate;
    private javax.swing.JButton btnCustomerDelete;
    private javax.swing.JButton btnCustomerRegister;
    private javax.swing.JButton btnCustomerSearch;
    private javax.swing.JButton btnCustomerUpdate;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtCarRegCategory;
    private javax.swing.JTextField txtCarRegColor;
    private javax.swing.JTextField txtCarRegID;
    private javax.swing.JTextField txtCarRegName;
    private javax.swing.JTextField txtCarRegNumber;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtCategoryRegID;
    private javax.swing.JTextArea txtCategoryView;
    private javax.swing.JTextField txtCustomerRegAddress;
    private javax.swing.JTextField txtCustomerRegFirstName;
    private javax.swing.JTextField txtCustomerRegID;
    private javax.swing.JTextField txtCustomerRegLastName;
    private javax.swing.JTextField txtCustomerRegMobile;
    private javax.swing.JTextField txtCustomerRegNICNumber;
    private javax.swing.JTextArea txtCustomerView;
    private javax.swing.JTextArea txtPatientView;
    private javax.swing.JTextField txtSearchCar;
    private javax.swing.JTextField txtSearchCategory;
    private javax.swing.JTextField txtSearchCustomer;
    // End of variables declaration//GEN-END:variables
}
